spring:
  datasource:
    initialization-mode: always
    password: ''
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
      show-sql: false
    properties:
      hibernate:
      format_sql: false
    show-sql: false
  profiles:
    active: test

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG